In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Simple universal functions

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

Using random arrays to demonstrate more universal functions

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 0.35715533, -0.62233984, -0.12582407, -0.34962885, -0.07246949,
        1.67134012,  1.36541482,  1.20373583, -0.45055498, -0.28288214])

In [9]:
B = np.random.randn(10)
B

array([-0.24935396,  1.11924645,  0.34696975, -0.2217382 ,  0.37919987,
       -0.37886441, -0.10414307, -1.25497123, -1.05817117, -0.98323535])

Add the values together in each location of two arrays

In [10]:
np.add(A,B)

array([ 0.10780137,  0.49690661,  0.22114569, -0.57136705,  0.30673038,
        1.29247571,  1.26127175, -0.05123539, -1.50872615, -1.26611749])

Find the maximum value in a location between two arrays

In [12]:
np.maximum(A,B)

array([ 0.35715533,  1.11924645,  0.34696975, -0.2217382 ,  0.37919987,
        1.67134012,  1.36541482,  1.20373583, -0.45055498, -0.28288214])