In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

Concatenate in numpy

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Combine by rows

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

Combine by column

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Concatenate in pandas

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

Specifying the axis to concatenate. axis=1 will create a DataFrame

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

Adding markers or keys to the concatenate using index hierarchy

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

These methods work the same for DataFrames as they did for Series

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0 -0.688612 -0.215176 -1.043661
1  0.958324 -1.501679  1.077069
2 -0.296276  0.487173  1.737024
3  0.038702  1.278585 -0.165837

In [14]:
dframe2

Y         Q         X
0 -1.494117 -0.914932 -0.687366
1  0.498504 -0.303111 -0.043536
2 -0.681515  1.457977  0.004933

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.688612 -0.215176 -1.043661
1       NaN  0.958324 -1.501679  1.077069
2       NaN -0.296276  0.487173  1.737024
3       NaN  0.038702  1.278585 -0.165837
0 -0.914932 -0.687366 -1.494117       NaN
1 -0.303111 -0.043536  0.498504       NaN
2  1.457977  0.004933 -0.681515       NaN

Ignoring an index in the concatenate

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.688612 -0.215176 -1.043661
1       NaN  0.958324 -1.501679  1.077069
2       NaN -0.296276  0.487173  1.737024
3       NaN  0.038702  1.278585 -0.165837
4 -0.914932 -0.687366 -1.494117       NaN
5 -0.303111 -0.043536  0.498504       NaN
6  1.457977  0.004933 -0.681515       NaN